"""empty message

Revision ID: 4f16b3dd4ccd
Revises: 497ebf7e5e77
Create Date: 2023-01-24 17:35:22.973738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f16b3dd4ccd'
down_revision = '497ebf7e5e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('veterinarian_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'veterinarian', ['veterinarian_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('veterinarian_id')

    # ### end Alembic commands ###
