"""empty message

Revision ID: 832d9aed2a57
Revises: e926f090fc3d
Create Date: 2023-02-18 12:00:32.675323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832d9aed2a57'
down_revision = 'e926f090fc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
