"""empty message

Revision ID: 866a780d8924
Revises: 566dbcbc6e62
Create Date: 2023-01-23 12:53:52.286614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866a780d8924'
down_revision = '566dbcbc6e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mascot_name', sa.Integer(), nullable=True))
        batch_op.drop_constraint('appointment_mascot_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mascot', ['mascot_name'], ['name'])
        batch_op.drop_column('mascot_id')

    with op.batch_alter_table('diet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mascot_name', sa.Integer(), nullable=True))
        batch_op.drop_constraint('diet_mascot_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mascot', ['mascot_name'], ['name'])
        batch_op.drop_column('mascot_id')

    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mascot_name', sa.Integer(), nullable=True))
        batch_op.drop_constraint('medicine_mascot_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mascot', ['mascot_name'], ['name'])
        batch_op.drop_column('mascot_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mascot_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('medicine_mascot_id_fkey', 'mascot', ['mascot_id'], ['id'])
        batch_op.drop_column('mascot_name')

    with op.batch_alter_table('diet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mascot_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('diet_mascot_id_fkey', 'mascot', ['mascot_id'], ['id'])
        batch_op.drop_column('mascot_name')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mascot_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('appointment_mascot_id_fkey', 'mascot', ['mascot_id'], ['id'])
        batch_op.drop_column('mascot_name')

    # ### end Alembic commands ###
