"""empty message

Revision ID: 880257148c2d
Revises: 973b982db28d
Create Date: 2023-01-20 18:20:00.960255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880257148c2d'
down_revision = '973b982db28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
