"""empty message

Revision ID: 973b982db28d
Revises: 
Create Date: 2023-01-14 11:56:21.509119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973b982db28d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('veterinarian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_name', sa.String(length=120), nullable=False),
    sa.Column('adress', sa.String(length=280), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adress'),
    sa.UniqueConstraint('clinic_name')
    )
    op.create_table('mascot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('species', sa.Enum('canine', 'feline', name='species'), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True),
    sa.Column('breed', sa.String(length=80), nullable=True),
    sa.Column('colour', sa.String(length=20), nullable=True),
    sa.Column('caracteristics', sa.String(length=400), nullable=True),
    sa.Column('img_1', sa.String(length=120), nullable=True),
    sa.Column('img_2', sa.String(length=120), nullable=True),
    sa.Column('img_3', sa.String(length=120), nullable=True),
    sa.Column('img_mimetype', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascot_id', sa.Integer(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['veterinarian.id'], ),
    sa.ForeignKeyConstraint(['mascot_id'], ['mascot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascot_id', sa.Integer(), nullable=True),
    sa.Column('foodname', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('times_a_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascot_id'], ['mascot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascot_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('times_a_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mascot_id'], ['mascot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicine')
    op.drop_table('diet')
    op.drop_table('appointment')
    op.drop_table('mascot')
    op.drop_table('veterinarian')
    op.drop_table('user')
    # ### end Alembic commands ###
