"""empty message

Revision ID: 9e5b404ad3ca
Revises: 832d9aed2a57
Create Date: 2023-02-18 12:12:51.788753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5b404ad3ca'
down_revision = '832d9aed2a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('veterinarian_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'veterinarian', ['veterinarian_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('veterinarian_id')

    # ### end Alembic commands ###
